global:
  image:
    repository: ghcr.io/epoch8/label-studio/label-studio
    tag: 1.8.0rq0-fix.1

  pgConfig:
    host: "${db_host}"
    port: ${db_port}
    userName: "${db_user}"
    dbName: "${db_name}"
    password:
      secretName: "${db_pass_secret_name}"
      secretKey: "${db_pass_secret_key}"
  
  extraEnvironmentVars:
    LABEL_STUDIO_USERNAME: ${ls_admin_username}
    LABEL_STUDIO_PASSWORD: ${ls_admin_password}
    LABEL_STUDIO_USER_TOKEN: ${ls_admin_token}

    LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"

  %{ if gcs_persistence != null }
  persistence:
    enabled: true
    type: gcs
    config:
      gcs:
        projectID: ${ gcs_persistence.project }
        bucket: ${ gcs_persistence.bucket }
        folder: ${ gcs_persistence.prefix }
  %{ else }
  persistence:
    enabled: false
  %{ endif ~}

app:
  deploymentStrategy:
    type: Recreate

  resources:
    requests:
      cpu: "${app_resources.requests.cpu}"
      memory: "${app_resources.requests.memory}"
    limits:
      cpu: "${app_resources.limits.cpu}"
      memory: "${app_resources.limits.memory}"

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    host: ${ls_domain}
    tls:
      - hosts:
          - ${ls_domain}
        secretName: ${ls_domain}-tls

rqworker:
  enabled: true

  queues:
    default:
      replicas: 1
      args: '"default", "critical", "high", "low"'
      resources:
        requests:
          cpu: "${app_resources.requests.cpu}"
          memory: "${app_resources.requests.memory}"
        limits:
          cpu: "${app_resources.limits.cpu}"
          memory: "${app_resources.limits.memory}"
    critical: null
    high: null
    low: null
  
  serviceAccount:
    create: true

postgresql:
  enabled: false

redis:
  enabled: true
